# type path mode user group age argument
d /srv/halfsphere                 0750 root       halfsphere - -
d /srv/halfsphere/apps            0750 root       halfsphere - -
d /srv/halfsphere/apps/halfsphere-web          0750 root halfsphere - -
d /srv/halfsphere/apps/halfsphere-web/releases 0750 root halfsphere - -
d /srv/halfsphere/apps/halfsphere-api          0750 root halfsphere - -
d /srv/halfsphere/apps/halfsphere-api/releases 0750 root halfsphere - -
d /srv/halfsphere/config          0750 root       halfsphere - -
d /srv/halfsphere/config/backup.d 0750 root       root       - -
d /srv/halfsphere/data            0750 halfsphere halfsphere - -
d /srv/halfsphere/logs            0750 halfsphere halfsphere - -
d /srv/halfsphere/backups         0700 root       root       - -
